name: Auto Commit

on:
  push:
    branches:
      - main  # Sur la branche principale
  schedule:
    - cron: '0 * * * *'  # Exécution toutes les heures

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "rania625"
          git config --global user.email "mikasanono923@gmail.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Automated commit" || echo "No changes to commit"
          git push
